"""Replace unique constraint with partial unique indexes

Revision ID: 09fcdb983690
Revises: a6da8c6f7b01
Create Date: 2026-02-08 00:52:07.500505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09fcdb983690'
down_revision: Union[str, None] = 'a6da8c6f7b01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_company_talent_values_company_job', 'company_talent_values', type_='unique')
    op.create_index('uq_company_talent_values_company_job_not_null', 'company_talent_values', ['company_id', 'job_category_id'], unique=True, postgresql_where=sa.text('job_category_id IS NOT NULL'))
    op.create_index('uq_company_talent_values_company_null_job', 'company_talent_values', ['company_id'], unique=True, postgresql_where=sa.text('job_category_id IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_company_talent_values_company_null_job', table_name='company_talent_values', postgresql_where=sa.text('job_category_id IS NULL'))
    op.drop_index('uq_company_talent_values_company_job_not_null', table_name='company_talent_values', postgresql_where=sa.text('job_category_id IS NOT NULL'))
    op.create_unique_constraint('uq_company_talent_values_company_job', 'company_talent_values', ['company_id', 'job_category_id'])
    # ### end Alembic commands ###
