"""Add updated_at to companies

Revision ID: 59c288f83b79
Revises: bf4ca5b7ccdb
Create Date: 2026-01-29 15:50:55.308761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59c288f83b79'
down_revision: Union[str, None] = 'bf4ca5b7ccdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'updated_at')
    # ### end Alembic commands ###
