"""merge 'questions' and 'contents' into 'itmes'

Revision ID: 5cbfb0b7f19e
Revises: 94831ceee69f
Create Date: 2026-02-13 19:41:05.128440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5cbfb0b7f19e'
down_revision: Union[str, None] = '94831ceee69f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cover_letters', sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_column('cover_letters', 'question')
    op.drop_column('cover_letters', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cover_letters', sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('cover_letters', sa.Column('question', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('cover_letters', 'items')
    # ### end Alembic commands ###
