"""Add company_talent_values table

Revision ID: a6da8c6f7b01
Revises: 59c288f83b79
Create Date: 2026-02-07 23:37:30.539309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a6da8c6f7b01'
down_revision: Union[str, None] = '59c288f83b79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_talent_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('job_category_id', sa.Integer(), nullable=True),
    sa.Column('values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['job_category_id'], ['job_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'job_category_id', name='uq_company_talent_values_company_job')
    )
    op.create_index('idx_company_talent_values_company', 'company_talent_values', ['company_id'], unique=False)
    op.create_index('idx_company_talent_values_job_category', 'company_talent_values', ['job_category_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_company_talent_values_job_category', table_name='company_talent_values')
    op.drop_index('idx_company_talent_values_company', table_name='company_talent_values')
    op.drop_table('company_talent_values')
    # ### end Alembic commands ###
