"""Add companies table

Revision ID: bf4ca5b7ccdb
Revises: ab0747d94301
Create Date: 2026-01-29 14:54:17.967941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf4ca5b7ccdb'
down_revision: Union[str, None] = 'ab0747d94301'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_constraint('user_specs_job_category_id_fkey', 'user_specs', type_='foreignkey')
    op.create_foreign_key(None, 'user_specs', 'job_categories', ['job_category_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_specs', type_='foreignkey')
    op.create_foreign_key('user_specs_job_category_id_fkey', 'user_specs', 'job_categories', ['job_category_id'], ['id'])
    op.drop_table('companies')
    # ### end Alembic commands ###
